config/routes.rb
Rails.application.routes.draw do
  resources :uploads
  resources :users
  get 'validations/index'

  root 'validations#index'

  resources :validations

  resources :photocopies

  resources :kts

  resources :examinations

  resources :admissions

  get ':admissions/:custshow/:id' => 'admissions#custshow'

  resources :users

  resources :uploads

  resources :emails

  resources :photos, only: [:new, :create, :index, :destroy]

  


  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admission.rb
class Admission < ApplicationRecord
	has_many :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/examination.rb
class Examination < ApplicationRecord
end

app/models/kt.rb
class Kt < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
	
    do_not_validate_attachment_file_type :image 
    has_attached_file :image
            
end

app/models/photocopie.rb
class Photocopie < ApplicationRecord
end

app/models/upload.rb
class Upload < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/validation.rb
class Validation < ApplicationRecord
end

app/controllers/kts_controller.rb
class KtsController < ApplicationController
	def index
		@testdata=Kt.all
		render json: @testdata
	end

	def show
		@kt = Kt.find(params[:id])
		render json: @kt
	end

	def create
		params.permit!
    	@kt = Kt.new(params[:kts])	
    	@kt.save
	end

end

app/controllers/validations_controller.rb
class ValidationsController < ApplicationController
	def index
		@testdata=Validation.all
		render json: @testdata
	end

	def show
		@validation = Validation.find(params[:id])
		render json: @validation
	end

	def new
	end

	def edit
		@validation = Validation.find(params[:id])
	end
	
	def create
		params.permit!
    	@validation = Validation.new(params[:validations])	
    	@validation.save
	end

	def destroy
	    @validation = Validation.find(params[:id])
	    @validation.destroy
	 
	    redirect_to validation_path
	end
end

app/helpers/admissions_helper.rb
module AdmissionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/first_helper.rb
module FirstHelper
end

app/helpers/kts_helper.rb
module KtsHelper
end

app/helpers/photocopies_helper.rb
module PhotocopiesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/validation_helper.rb
module ValidationHelper
end

app/views/validations/edit.html.erb
<h1>Edit Content</h1>
<%= form_for :validation , url:/validations do |f| %>
  <p>
    <%= f.label :year_ent%><br>
    <%= f.text_field :year_ent %>
  </p>
  <p>
    <%= f.label :branch_ent %><br>
    <%= f.text_field :branch_ent %>
  </p>
  <p>
    <%= f.label :fe_ent %><br>
    <%= f.text_field :fe_ent %>
  </p>
  <p>
    <%= f.label :se_ent %><br>
    <%= f.text_field :se_ent %>
  </p>
  <p>
    <%= f.label :te_ent %><br>
    <%= f.text_field :te_ent %>
  </p>
  <p>
    <%= f.label :be_ent %><br>
    <%= f.text_area :be_ent %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/validations/new.html.erb
<h1>New Content</h1>
<%= form_for :validation, url: validations_path  do |f| %>
  <p>
    <%= f.label :year_ent%><br>
    <%= f.text_field :year_ent %>
  </p>
  <p>
    <%= f.label :branch_ent %><br>
    <%= f.text_field :branch_ent %>
  </p>
  <p>
    <%= f.label :fe_ent %><br>
    <%= f.text_field :fe_ent %>
  </p>
  <p>
    <%= f.label :se_ent %><br>
    <%= f.text_field :se_ent %>
  </p>
  <p>
    <%= f.label :te_ent %><br>
    <%= f.text_field :te_ent %>
  </p>
  <p>
    <%= f.label :be_ent %><br>
    <%= f.text_area :be_ent %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/validations/show.html.erb
<h2>hgadvhvchsavh</h2>